name: MLOps CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout du code
      uses: actions/checkout@v4

    - name: ğŸ Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: ğŸ§° Installer les dÃ©pendances
      run: |
        python -m venv mlops_env
        source mlops_env/bin/activate
        pip install -r requirements.txt

    - name: ğŸ§¹ Lint + format
      run: |
        source mlops_env/bin/activate
        make lint-all || true

    - name: ğŸ§ª Lancer les tests
      run: |
        source mlops_env/bin/activate
        make test || true

    - name: ğŸš€ DÃ©ploiement (make deploy)
      run: |
        source mlops_env/bin/activate
        make deploy

    - name: ğŸ“¤ Upload du modÃ¨le entraÃ®nÃ©
      uses: actions/upload-artifact@v4
      with:
        name: best_model
        path: resultat/best_model.pka
